# This workflow will run tests using node and then publish a package to NPM when a release is released

name: Publish Package to NPM

on:
  release:
    types:
      - released

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v4
        with:
          node-version: '16.14.0'

      - name: Use NPM 8.5.3
        run: npm i -g npm@8.5.3

      - name: Set the package version
        run: npm version --no-git-tag-version ${{github.event.release.tag_name}}

      - name: Publish on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
